server:
  port: 8080
spring:
  application:
    name: "pharmacyCA"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
  data:
    mongodb:
      uri: "mongodb+srv://BrianSammit:073Brian@cluster0.r5ne7n0.mongodb.net/db-products?retryWrites=true&w=majority"
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
